image: python:3.6.2

pipelines:
  default:
      - step:
          name: Tests
          script:
            - python -m unittest discover tests
  branches:
    master:
      - step:
          name: Tests
          script:
            - python -m unittest discover tests
      - step:
          name: Deploy To PyPI
          script:
            - bash -e deploy.bash