beauty_print_parameters = [{'title': 'Feature/pr', 'description': '* Edit README\r\n\r\n* README.md edited online with Bitbucket', 'participants': [{'role': 'REVIEWER', 'participated_on': None, 'type': 'participant', 'approved': False, 'user': {'username': 'bookinman', 'display_name': 'Emir Amanbekov', 'type': 'user', 'uuid': '{e9c4267a-4b16-48ba-89c5-ba7ec695eeef}', 'links': {'self': {'href': 'https://api.bitbucket.org/2.0/users/bookinman'}, 'html': {'href': 'https://bitbucket.org/bookinman/'}, 'avatar': {'href': 'https://bitbucket.org/account/bookinman/avatar/32/'}}}}], 'links': {'decline': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/decline'}, 'commits': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/commits'}, 'self': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3'}, 'comments': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/comments'}, 'merge': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/merge'}, 'html': {'href': 'https://bitbucket.org/bookinman/test-repo/pull-requests/3'}, 'activity': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/activity'}, 'diff': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/diff'}, 'approve': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/approve'}, 'statuses': {'href': 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/3/statuses'}}}]

beauty_print_response = '____________________\nTitle: Feature/pr\nDescription: * Edit README\r\n\r\n* README.md edited online with Bitbucket\nLink: https://bitbucket.org/bookinman/test-repo/pull-requests/3'

pr_list_response = [{'participants': [{'role': 'REVIEWER', 'user': {'username': 'bookinman'}, 'approved': False}], 'description': '* Edit README\r\n\r\n* README.md edited online with Bitbucket', 'links': {'html': {'href': 'https://bitbucket.org/bookinman/test-repo/pull-requests/3'}}, 'title': 'Feature/pr'}]

get_request_response = {'values': [{'participants': [{'role': 'REVIEWER', 'user': {'username': 'bookinman'}, 'approved': False}], 'description': '* Edit README\r\n\r\n* README.md edited online with Bitbucket', 'links': {'html': {'href': 'https://bitbucket.org/bookinman/test-repo/pull-requests/3'}}, 'title': 'Feature/pr'}]}

get_request_url = 'https://api.bitbucket.org/2.0/repositories/bookinman/test-repo/pullrequests/?q=state="OPEN"+AND+reviewers.username="bookinman"&fields=values.title,values.links.html,values.description,values.participants.role,values.participants.approved,values.participants.user.username'

get_request_auth = {'Authorization': 'Basic Ym9va2lubWFuOnBhc3N3b3Jk'}
